require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AcaDataController do

  # This should return the minimal set of attributes required to create a valid
  # AcaDatum. As you add validations to AcaDatum, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AcaDataController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all aca_data as @aca_data" do
      aca_datum = AcaDatum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:aca_data).should eq([aca_datum])
    end
  end

  describe "GET show" do
    it "assigns the requested aca_datum as @aca_datum" do
      aca_datum = AcaDatum.create! valid_attributes
      get :show, {:id => aca_datum.to_param}, valid_session
      assigns(:aca_datum).should eq(aca_datum)
    end
  end

  describe "GET new" do
    it "assigns a new aca_datum as @aca_datum" do
      get :new, {}, valid_session
      assigns(:aca_datum).should be_a_new(AcaDatum)
    end
  end

  describe "GET edit" do
    it "assigns the requested aca_datum as @aca_datum" do
      aca_datum = AcaDatum.create! valid_attributes
      get :edit, {:id => aca_datum.to_param}, valid_session
      assigns(:aca_datum).should eq(aca_datum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AcaDatum" do
        expect {
          post :create, {:aca_datum => valid_attributes}, valid_session
        }.to change(AcaDatum, :count).by(1)
      end

      it "assigns a newly created aca_datum as @aca_datum" do
        post :create, {:aca_datum => valid_attributes}, valid_session
        assigns(:aca_datum).should be_a(AcaDatum)
        assigns(:aca_datum).should be_persisted
      end

      it "redirects to the created aca_datum" do
        post :create, {:aca_datum => valid_attributes}, valid_session
        response.should redirect_to(AcaDatum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved aca_datum as @aca_datum" do
        # Trigger the behavior that occurs when invalid params are submitted
        AcaDatum.any_instance.stub(:save).and_return(false)
        post :create, {:aca_datum => {}}, valid_session
        assigns(:aca_datum).should be_a_new(AcaDatum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AcaDatum.any_instance.stub(:save).and_return(false)
        post :create, {:aca_datum => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested aca_datum" do
        aca_datum = AcaDatum.create! valid_attributes
        # Assuming there are no other aca_data in the database, this
        # specifies that the AcaDatum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AcaDatum.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => aca_datum.to_param, :aca_datum => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested aca_datum as @aca_datum" do
        aca_datum = AcaDatum.create! valid_attributes
        put :update, {:id => aca_datum.to_param, :aca_datum => valid_attributes}, valid_session
        assigns(:aca_datum).should eq(aca_datum)
      end

      it "redirects to the aca_datum" do
        aca_datum = AcaDatum.create! valid_attributes
        put :update, {:id => aca_datum.to_param, :aca_datum => valid_attributes}, valid_session
        response.should redirect_to(aca_datum)
      end
    end

    describe "with invalid params" do
      it "assigns the aca_datum as @aca_datum" do
        aca_datum = AcaDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AcaDatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => aca_datum.to_param, :aca_datum => {}}, valid_session
        assigns(:aca_datum).should eq(aca_datum)
      end

      it "re-renders the 'edit' template" do
        aca_datum = AcaDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AcaDatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => aca_datum.to_param, :aca_datum => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested aca_datum" do
      aca_datum = AcaDatum.create! valid_attributes
      expect {
        delete :destroy, {:id => aca_datum.to_param}, valid_session
      }.to change(AcaDatum, :count).by(-1)
    end

    it "redirects to the aca_data list" do
      aca_datum = AcaDatum.create! valid_attributes
      delete :destroy, {:id => aca_datum.to_param}, valid_session
      response.should redirect_to(aca_data_url)
    end
  end

end
